// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PoxterMilitar.Models;

/// <summary>
/// usuarios pacientes
/// </summary>
public partial class patientes
{
    public string name_p { get; set; }

    public string lastname_p { get; set; }

    public string gender_p { get; set; }

    public long height_p { get; set; }

    public long weight_p { get; set; }

    public string email_p { get; set; }

    public long cellphone_p { get; set; }

    public long id_p { get; set; }
}