// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PoxterMilitar.Models;

public partial class users_poxter
{
    internal string telefono_u;

    public long id_u { get; set; }
    public string name_u { get; set; }
    public string lastname_u { get; set; }
    public string email_u { get; set; }
    public string area_u { get; set; }
    public string password_u { get; set; }
    public string username_u { get; set; }
    public string telephone_u { get; set; }
}